CREATE PROCEDURE ETL_BRANCH_INIT()
AS
BEGIN
	INSERT INTO ETL_BRANCH(BRANCHCODE, BRANCHNAME)
	VALUES(-1, '-No Branch-');
	
	INSERT INTO ETL_BRANCH(BRANCHCODE, BRANCHNAME)
	SELECT T0."BPLId", T0."BPLName"
	FROM "OBPL" T0;
END
