CREATE VIEW "Z_TEST_PRODUCTION_20250925"."MIS_PROFIT_LOSS_COST_CENTER" ( "Date", "FromDate", "ToDate", "AcctCode", "FatherNum", "Levels", "AcctName", "ProfitCode", "Debit", "Credit", "current period", "level 5 acctcode", "level 5 acctname", "level 5 levels", "level 4 acctcode", "level 4 acctname", "level 4 levels", "level 3 acctcode", "level 3 acctname", "level 3 levels", "level 2 acctcode", "level 2 acctname", "level 2 levels", "level 1 acctcode", "level 1 acctname", "level 1 levels" ) AS select  jdt."RefDate"   "Date"
, jdt."RefDate"  "FromDate"
, jdt."RefDate"  "ToDate"
,act."AcctCode"
,act."FatherNum" 
,act."Levels"
,act."AcctName", jt1."ProfitCode",
jt1."Debit",jt1."Credit",(jt1."Debit"-jt1."Credit") "current period"
   -------------------------------------------------
  ,(case when act5."Levels"=5 then act5."AcctCode"
  when act4."Levels"=5 then act4."AcctCode"
  when act3."Levels"=5 then act3."AcctCode"
  when act2."Levels"=5 then act2."AcctCode"
  when act1."Levels"=5 then act1."AcctCode"
  when act."Levels"=5 then act."AcctCode" 
  else NULL end ) "level 5 acctcode"
  ,(case when act5."Levels"=5 then act5."AcctName"
  when act4."Levels"=5 then act4."AcctName"
  when act3."Levels"=5 then act3."AcctName"
  when act2."Levels"=5 then act2."AcctName"
  when act1."Levels"=5 then act1."AcctName"
  when act."Levels"=5 then act."AcctName" 
  else NULL end ) "level 5 acctname"
    ,(case when act5."Levels"=5 then act5."Levels"
  when act4."Levels"=5 then act4."Levels"
  when act3."Levels"=5 then act3."Levels"
  when act2."Levels"=5 then act2."Levels"
  when act1."Levels"=5 then act1."Levels"
  when act."Levels"=5 then act."Levels" 
  else NULL end ) "level 5 levels"
    ------------------------------------------------
  ,(case when act5."Levels"=4 then act5."AcctCode"
  when act4."Levels"=4 then act4."AcctCode"
  when act3."Levels"=4 then act3."AcctCode"
  when act2."Levels"=4 then act2."AcctCode"
  when act1."Levels"=4 then act1."AcctCode"
  when act."Levels"=4 then act."AcctCode" 
  else NULL end ) "level 4 acctcode"
  ,(case when act5."Levels"=4 then act5."AcctName"
  when act4."Levels"=4 then act4."AcctName"
  when act3."Levels"=4 then act3."AcctName"
  when act2."Levels"=4 then act2."AcctName"
  when act1."Levels"=4 then act1."AcctName"
  when act."Levels"=4 then act."AcctName" 
  else NULL end ) "level 4 acctname"
   ,(case when act5."Levels"=4 then act5."Levels"
  when act4."Levels"=4 then act4."Levels"
  when act3."Levels"=4 then act3."Levels"
  when act2."Levels"=4 then act2."Levels"
  when act1."Levels"=4 then act1."Levels"
  when act."Levels"=4 then act."Levels" 
  else NULL end ) "level 4 levels"
    ------------------------------------------------------------
  ,(case when act5."Levels"=3 then act5."AcctCode"
  when act4."Levels"=3 then act4."AcctCode"
  when act3."Levels"=3 then act3."AcctCode"
  when act2."Levels"=3 then act2."AcctCode"
  when act1."Levels"=3 then act1."AcctCode"
  when act."Levels"=3 then act."AcctCode" 
  else NULL end ) "level 3 acctcode"
  ,(case when act5."Levels"=3 then act5."AcctName"
  when act4."Levels"=3 then act4."AcctName"
  when act3."Levels"=3 then act3."AcctName"
  when act2."Levels"=3 then act2."AcctName"
  when act1."Levels"=3 then act1."AcctName"
  when act."Levels"=3 then act."AcctName" 
  else NULL end ) "level 3 acctname"
    ,(case when act5."Levels"=3 then act5."Levels"
  when act4."Levels"=3 then act4."Levels"
  when act3."Levels"=3 then act3."Levels"
  when act2."Levels"=3 then act2."Levels"
  when act1."Levels"=3 then act1."Levels"
  when act."Levels"=3 then act."Levels" 
  else NULL end ) "level 3 levels"
  ------------------------------------------------------
,(case when act5."Levels"=2 then act5."AcctCode"
  when act4."Levels"=2 then act4."AcctCode"
  when act3."Levels"=2 then act3."AcctCode"
  when act2."Levels"=2 then act2."AcctCode"
  when act1."Levels"=2 then act1."AcctCode"
  when act."Levels"=2 then act."AcctCode" 
  else NULL end ) "level 2 acctcode"
,(case when act5."Levels"=2 then act5."AcctName"
  when act4."Levels"=2 then act4."AcctName"
  when act3."Levels"=2 then act3."AcctName"
  when act2."Levels"=2 then act2."AcctName"
  when act1."Levels"=2 then act1."AcctName"
  when act."Levels"=2 then act."AcctName" 
  else NULL end ) "level 2 acctname"
  ,(case when act5."Levels"=2 then act5."Levels"
  when act4."Levels"=2 then act4."Levels"
  when act3."Levels"=2 then act3."Levels"
  when act2."Levels"=2 then act2."Levels"
  when act1."Levels"=2 then act1."Levels"
  when act."Levels"=2 then act."Levels" 
  else NULL end ) "level 2 levels"
-------------------------------------------------------------
,(case when act5."Levels"=1 then act5."AcctCode"
  when act4."Levels"=1 then act4."AcctCode"
  when act3."Levels"=1 then act3."AcctCode"
  when act2."Levels"=1 then act2."AcctCode"
  when act1."Levels"=1 then act1."AcctCode"
  when act."Levels"=1 then act."AcctCode" 
  else NULL end ) "level 1 acctcode"
,(case when act5."Levels"=1 then act5."AcctName"
  when act4."Levels"=1 then act4."AcctName"
  when act3."Levels"=1 then act3."AcctName"
  when act2."Levels"=1 then act2."AcctName"
  when act1."Levels"=1 then act1."AcctName"
  when act."Levels"=1 then act."AcctName" 
  else NULL end ) "level 1 acctname"
  ,(case when act5."Levels"=1 then act5."Levels"
  when act4."Levels"=1 then act4."Levels"
  when act3."Levels"=1 then act3."Levels"
  when act2."Levels"=1 then act2."Levels"
  when act1."Levels"=1 then act1."Levels"
  when act."Levels"=1 then act."Levels" 
  else NULL end ) "level 1 levels"

from ojdt jdt
inner join jdt1 jt1 on jdt."TransId"=jt1."TransId"
left outer join oact act on act."AcctCode"=jt1."Account"
left outer join oact act1 on act."FatherNum"=act1."AcctCode"
left outer join oact act2 on act1."FatherNum"=act2."AcctCode"
left outer join oact act3 on act2."FatherNum"=act3."AcctCode"
left outer join oact act4 on act3."FatherNum"=act4."AcctCode"
left outer join oact act5 on act4."FatherNum"=act5."AcctCode"

where (case when act5."Levels"=1 then act5."AcctName"
  when act4."Levels"=1 then act4."AcctName"
  when act3."Levels"=1 then act3."AcctName"
  when act2."Levels"=1 then act2."AcctName"
  when act1."Levels"=1 then act1."AcctName"
  when act."Levels"=1 then act."AcctName" 
  else NULL end ) in ('Revenue','Expenditure') WITH READ ONLY