CREATE PROCEDURE ETL_PROJECT_INIT()
AS
BEGIN
	INSERT INTO ETL_PROJECT(PROJECTCODE, PROJECTNAME)
	VALUES('-', '-No Project-');
	
	INSERT INTO ETL_PROJECT(PROJECTCODE, PROJECTNAME)
	SELECT T0."PrjCode", T0."PrjName"
	FROM "OPRJ" T0;
END
