CREATE PROCEDURE ETL_LOCATION_INIT()
AS
BEGIN
	INSERT INTO ETL_LOCATION(LOCCODE, LOCNAME)
	VALUES(-1, '-No Location-');
	
	INSERT INTO ETL_LOCATION(LOCCODE, LOCNAME)
	SELECT T0."Code", T0."Location"
	FROM "OLCT" T0;
	
END
