CREATE PROCEDURE OPRJ_DELTA()
AS
BEGIN
	
		DELETE FROM ETL_PROJECT WHERE PROJECTCODE IN (SELECT "PrjCode" FROM OPRJ_DELTA_TABLE);
		INSERT INTO ETL_PROJECT(PROJECTCODE, PROJECTNAME)
		SELECT T0."PrjCode", T0."PrjName"
		FROM "OPRJ" T0 
		INNER JOIN OPRJ_DELTA_TABLE TEMP ON T0."PrjCode" = TEMP."PrjCode"
		WHERE TEMP.OPT IN ('I', 'U');
END
