CREATE PROCEDURE OFPR_DELTA()
AS
BEGIN
	
		DELETE FROM ETL_PERIOD WHERE PERIODENTRY IN (SELECT "AbsEntry" FROM OFPR_DELTA_TABLE);
		INSERT INTO ETL_PERIOD(PERIODENTRY, PERIODCODE, PERIODNAME, F_REFDATE, T_REFDATE)
		SELECT T0."AbsEntry", T0."Code", T0."Name", T0."F_RefDate", T0."T_RefDate"
		FROM "OFPR" T0 
		INNER JOIN OFPR_DELTA_TABLE TEMP ON T0."AbsEntry" = TEMP."AbsEntry"
		WHERE TEMP.OPT IN ('I', 'U');
END
