CREATE VIEW "Z_TEST_PRODUCTION_20250925"."LEVEL_ACCOUNT" ( "level 1 acctname", "level 2 acctname", "level 3 acctname", "level 4 acctname", "level 5 acctname" ) AS select distinct
(case when act5."Levels"=1 then act5."AcctName"
  when act4."Levels"=1 then act4."AcctName"
  when act3."Levels"=1 then act3."AcctName"
  when act2."Levels"=1 then act2."AcctName"
  when act1."Levels"=1 then act1."AcctName"
  when act."Levels"=1 then act."AcctName" 
  else '' end ) "level 1 acctname"
 ,(case when act5."Levels"=2 then act5."AcctName"
  when act4."Levels"=2 then act4."AcctName"
  when act3."Levels"=2 then act3."AcctName"
  when act2."Levels"=2 then act2."AcctName"
  when act1."Levels"=2 then act1."AcctName"
  when act."Levels"=2 then act."AcctName" 
  else '' end ) "level 2 acctname"
,(case when act5."Levels"=3 then act5."AcctName"
  when act4."Levels"=3 then act4."AcctName"
  when act3."Levels"=3 then act3."AcctName"
  when act2."Levels"=3 then act2."AcctName"
  when act1."Levels"=3 then act1."AcctName"
  when act."Levels"=3 then act."AcctName" 
  else '' end ) "level 3 acctname"
   ,(case when act5."Levels"=4 then act5."AcctName"
  when act4."Levels"=4 then act4."AcctName"
  when act3."Levels"=4 then act3."AcctName"
  when act2."Levels"=4 then act2."AcctName"
  when act1."Levels"=4 then act1."AcctName"
  when act."Levels"=4 then act."AcctName" 
  else '' end ) "level 4 acctname"
  ,(case when act5."Levels"=5 then act5."AcctName"
  when act4."Levels"=5 then act4."AcctName"
  when act3."Levels"=5 then act3."AcctName"
  when act2."Levels"=5 then act2."AcctName"
  when act1."Levels"=5 then act1."AcctName"
  when act."Levels"=5 then act."AcctName" 
  else '' end ) "level 5 acctname"

from OACT ACT
left outer join oact act1 on act."FatherNum"=act1."AcctCode"
left outer join oact act2 on act1."FatherNum"=act2."AcctCode"
left outer join oact act3 on act2."FatherNum"=act3."AcctCode"
left outer join oact act4 on act3."FatherNum"=act4."AcctCode"
left outer join oact act5 on act4."FatherNum"=act5."AcctCode" WITH READ ONLY