CREATE PROCEDURE ETL_OCRD_INIT()
AS
BEGIN
	INSERT INTO ETL_OCRD(CARDCODE, CARDNAME, CardType, GROUPCODE, COUNTRY, TERRITORY, 
			Property01,
			Property02,
			Property03,
			Property04,
			Property05,
			Property06,
			Property07,
			Property08,
			Property09 ,
			Property10 ,
			Property11 ,
			Property12 ,
			Property13 ,
			Property14 ,
			Property15 ,
			Property16 ,
			Property17 ,
			Property18 ,
			Property19 ,
			Property20 ,
			Property21 ,
			Property22 ,
			Property23 ,
			Property24 ,
			Property25 ,
			Property26 ,
			Property27 ,
			Property28 ,
			Property29 ,
			Property30 ,
			Property31 ,
			Property32 ,
			Property33 ,
			Property34 ,
			Property35 ,
			Property36 ,
			Property37 ,
			Property38 ,
			Property39 ,
			Property40 ,
			Property41 ,
			Property42 ,
			Property43 ,
			Property44 ,
			Property45 ,
			Property46 ,
			Property47 ,
			Property48 ,
			Property49 ,
			Property50 ,
			Property51 ,
			Property52 ,
			Property53 ,
			Property54 ,
			Property55 ,
			Property56 ,
			Property57 ,
			Property58 ,
			Property59 ,
			Property60 ,
			Property61 ,
			Property62 ,
			Property63 ,
			Property64 )
		SELECT T0."CardCode", T0."CardName", T0."CardType", T0."GroupCode", T0."Country", IFNULL(T0."Territory", -2),
		(CASE T0."QryGroup1" WHEN 'N' THEN '' ELSE (SELECT T1."GroupName" FROM OCQG T1 WHERE T1."GroupCode" = 1) END) AS PROPERTY01,
		(CASE T0."QryGroup2" WHEN 'N' THEN '' ELSE (SELECT T1."GroupName" FROM OCQG T1 WHERE T1."GroupCode" = 2) END) AS PROPERTY02,
		(CASE T0."QryGroup3" WHEN 'N' THEN '' ELSE (SELECT T1."GroupName" FROM OCQG T1 WHERE T1."GroupCode" = 3) END) AS PROPERTY03,
		(CASE T0."QryGroup4" WHEN 'N' THEN '' ELSE (SELECT T1."GroupName" FROM OCQG T1 WHERE T1."GroupCode" = 4) END) AS PROPERTY04,
		(CASE T0."QryGroup5" WHEN 'N' THEN '' ELSE (SELECT T1."GroupName" FROM OCQG T1 WHERE T1."GroupCode" = 5) END) AS PROPERTY05,
		(CASE T0."QryGroup6" WHEN 'N' THEN '' ELSE (SELECT T1."GroupName" FROM OCQG T1 WHERE T1."GroupCode" = 6) END) AS PROPERTY06,
		(CASE T0."QryGroup7" WHEN 'N' THEN '' ELSE (SELECT T1."GroupName" FROM OCQG T1 WHERE T1."GroupCode" = 7) END) AS PROPERTY07,
		(CASE T0."QryGroup8" WHEN 'N' THEN '' ELSE (SELECT T1."GroupName" FROM OCQG T1 WHERE T1."GroupCode" = 8) END) AS PROPERTY08,
		(CASE T0."QryGroup9" WHEN 'N' THEN '' ELSE (SELECT T1."GroupName" FROM OCQG T1 WHERE T1."GroupCode" = 9) END) AS PROPERTY09,
		(CASE T0."QryGroup10" WHEN 'N' THEN '' ELSE (SELECT T1."GroupName" FROM OCQG T1 WHERE T1."GroupCode" = 10) END) AS PROPERTY10,
		(CASE T0."QryGroup11" WHEN 'N' THEN '' ELSE (SELECT T1."GroupName" FROM OCQG T1 WHERE T1."GroupCode" = 11) END) AS PROPERTY11,
		(CASE T0."QryGroup12" WHEN 'N' THEN '' ELSE (SELECT T1."GroupName" FROM OCQG T1 WHERE T1."GroupCode" = 12) END) AS PROPERTY12,
		(CASE T0."QryGroup13" WHEN 'N' THEN '' ELSE (SELECT T1."GroupName" FROM OCQG T1 WHERE T1."GroupCode" = 13) END) AS PROPERTY13,
		(CASE T0."QryGroup14" WHEN 'N' THEN '' ELSE (SELECT T1."GroupName" FROM OCQG T1 WHERE T1."GroupCode" = 14) END) AS PROPERTY14,
		(CASE T0."QryGroup15" WHEN 'N' THEN '' ELSE (SELECT T1."GroupName" FROM OCQG T1 WHERE T1."GroupCode" = 15) END) AS PROPERTY15,
		(CASE T0."QryGroup16" WHEN 'N' THEN '' ELSE (SELECT T1."GroupName" FROM OCQG T1 WHERE T1."GroupCode" = 16) END) AS PROPERTY16,
		(CASE T0."QryGroup17" WHEN 'N' THEN '' ELSE (SELECT T1."GroupName" FROM OCQG T1 WHERE T1."GroupCode" = 17) END) AS PROPERTY17,
		(CASE T0."QryGroup18" WHEN 'N' THEN '' ELSE (SELECT T1."GroupName" FROM OCQG T1 WHERE T1."GroupCode" = 18) END) AS PROPERTY18,
		(CASE T0."QryGroup19" WHEN 'N' THEN '' ELSE (SELECT T1."GroupName" FROM OCQG T1 WHERE T1."GroupCode" = 19) END) AS PROPERTY19,
		(CASE T0."QryGroup20" WHEN 'N' THEN '' ELSE (SELECT T1."GroupName" FROM OCQG T1 WHERE T1."GroupCode" = 20) END) AS PROPERTY20,
		(CASE T0."QryGroup21" WHEN 'N' THEN '' ELSE (SELECT T1."GroupName" FROM OCQG T1 WHERE T1."GroupCode" = 21) END) AS PROPERTY21,
		(CASE T0."QryGroup22" WHEN 'N' THEN '' ELSE (SELECT T1."GroupName" FROM OCQG T1 WHERE T1."GroupCode" = 22) END) AS PROPERTY22,
		(CASE T0."QryGroup23" WHEN 'N' THEN '' ELSE (SELECT T1."GroupName" FROM OCQG T1 WHERE T1."GroupCode" = 23) END) AS PROPERTY23,
		(CASE T0."QryGroup24" WHEN 'N' THEN '' ELSE (SELECT T1."GroupName" FROM OCQG T1 WHERE T1."GroupCode" = 24) END) AS PROPERTY24,
		(CASE T0."QryGroup25" WHEN 'N' THEN '' ELSE (SELECT T1."GroupName" FROM OCQG T1 WHERE T1."GroupCode" = 25) END) AS PROPERTY25,
		(CASE T0."QryGroup26" WHEN 'N' THEN '' ELSE (SELECT T1."GroupName" FROM OCQG T1 WHERE T1."GroupCode" = 26) END) AS PROPERTY26,
		(CASE T0."QryGroup27" WHEN 'N' THEN '' ELSE (SELECT T1."GroupName" FROM OCQG T1 WHERE T1."GroupCode" = 27) END) AS PROPERTY27,
		(CASE T0."QryGroup28" WHEN 'N' THEN '' ELSE (SELECT T1."GroupName" FROM OCQG T1 WHERE T1."GroupCode" = 28) END) AS PROPERTY28,
		(CASE T0."QryGroup29" WHEN 'N' THEN '' ELSE (SELECT T1."GroupName" FROM OCQG T1 WHERE T1."GroupCode" = 29) END) AS PROPERTY29,
		(CASE T0."QryGroup30" WHEN 'N' THEN '' ELSE (SELECT T1."GroupName" FROM OCQG T1 WHERE T1."GroupCode" = 30) END) AS PROPERTY30,
		(CASE T0."QryGroup31" WHEN 'N' THEN '' ELSE (SELECT T1."GroupName" FROM OCQG T1 WHERE T1."GroupCode" = 31) END) AS PROPERTY31,
		(CASE T0."QryGroup32" WHEN 'N' THEN '' ELSE (SELECT T1."GroupName" FROM OCQG T1 WHERE T1."GroupCode" = 32) END) AS PROPERTY32,
		(CASE T0."QryGroup33" WHEN 'N' THEN '' ELSE (SELECT T1."GroupName" FROM OCQG T1 WHERE T1."GroupCode" = 33) END) AS PROPERTY33,
		(CASE T0."QryGroup34" WHEN 'N' THEN '' ELSE (SELECT T1."GroupName" FROM OCQG T1 WHERE T1."GroupCode" = 34) END) AS PROPERTY34,
		(CASE T0."QryGroup35" WHEN 'N' THEN '' ELSE (SELECT T1."GroupName" FROM OCQG T1 WHERE T1."GroupCode" = 35) END) AS PROPERTY35,
		(CASE T0."QryGroup36" WHEN 'N' THEN '' ELSE (SELECT T1."GroupName" FROM OCQG T1 WHERE T1."GroupCode" = 36) END) AS PROPERTY36,
		(CASE T0."QryGroup37" WHEN 'N' THEN '' ELSE (SELECT T1."GroupName" FROM OCQG T1 WHERE T1."GroupCode" = 37) END) AS PROPERTY37,
		(CASE T0."QryGroup38" WHEN 'N' THEN '' ELSE (SELECT T1."GroupName" FROM OCQG T1 WHERE T1."GroupCode" = 38) END) AS PROPERTY38,
		(CASE T0."QryGroup39" WHEN 'N' THEN '' ELSE (SELECT T1."GroupName" FROM OCQG T1 WHERE T1."GroupCode" = 39) END) AS PROPERTY39,
		(CASE T0."QryGroup40" WHEN 'N' THEN '' ELSE (SELECT T1."GroupName" FROM OCQG T1 WHERE T1."GroupCode" = 40) END) AS PROPERTY40,
		(CASE T0."QryGroup41" WHEN 'N' THEN '' ELSE (SELECT T1."GroupName" FROM OCQG T1 WHERE T1."GroupCode" = 41) END) AS PROPERTY41,
		(CASE T0."QryGroup42" WHEN 'N' THEN '' ELSE (SELECT T1."GroupName" FROM OCQG T1 WHERE T1."GroupCode" = 42) END) AS PROPERTY42,
		(CASE T0."QryGroup43" WHEN 'N' THEN '' ELSE (SELECT T1."GroupName" FROM OCQG T1 WHERE T1."GroupCode" = 43) END) AS PROPERTY43,
		(CASE T0."QryGroup44" WHEN 'N' THEN '' ELSE (SELECT T1."GroupName" FROM OCQG T1 WHERE T1."GroupCode" = 44) END) AS PROPERTY44,
		(CASE T0."QryGroup45" WHEN 'N' THEN '' ELSE (SELECT T1."GroupName" FROM OCQG T1 WHERE T1."GroupCode" = 45) END) AS PROPERTY45,
		(CASE T0."QryGroup46" WHEN 'N' THEN '' ELSE (SELECT T1."GroupName" FROM OCQG T1 WHERE T1."GroupCode" = 46) END) AS PROPERTY46,
		(CASE T0."QryGroup47" WHEN 'N' THEN '' ELSE (SELECT T1."GroupName" FROM OCQG T1 WHERE T1."GroupCode" = 47) END) AS PROPERTY47,
		(CASE T0."QryGroup48" WHEN 'N' THEN '' ELSE (SELECT T1."GroupName" FROM OCQG T1 WHERE T1."GroupCode" = 48) END) AS PROPERTY48,
		(CASE T0."QryGroup49" WHEN 'N' THEN '' ELSE (SELECT T1."GroupName" FROM OCQG T1 WHERE T1."GroupCode" = 49) END) AS PROPERTY49,
		(CASE T0."QryGroup50" WHEN 'N' THEN '' ELSE (SELECT T1."GroupName" FROM OCQG T1 WHERE T1."GroupCode" = 50) END) AS PROPERTY50,
		(CASE T0."QryGroup51" WHEN 'N' THEN '' ELSE (SELECT T1."GroupName" FROM OCQG T1 WHERE T1."GroupCode" = 51) END) AS PROPERTY51,
		(CASE T0."QryGroup52" WHEN 'N' THEN '' ELSE (SELECT T1."GroupName" FROM OCQG T1 WHERE T1."GroupCode" = 52) END) AS PROPERTY52,
		(CASE T0."QryGroup53" WHEN 'N' THEN '' ELSE (SELECT T1."GroupName" FROM OCQG T1 WHERE T1."GroupCode" = 53) END) AS PROPERTY53,
		(CASE T0."QryGroup54" WHEN 'N' THEN '' ELSE (SELECT T1."GroupName" FROM OCQG T1 WHERE T1."GroupCode" = 54) END) AS PROPERTY54,
		(CASE T0."QryGroup55" WHEN 'N' THEN '' ELSE (SELECT T1."GroupName" FROM OCQG T1 WHERE T1."GroupCode" = 55) END) AS PROPERTY55,
		(CASE T0."QryGroup56" WHEN 'N' THEN '' ELSE (SELECT T1."GroupName" FROM OCQG T1 WHERE T1."GroupCode" = 56) END) AS PROPERTY56,
		(CASE T0."QryGroup57" WHEN 'N' THEN '' ELSE (SELECT T1."GroupName" FROM OCQG T1 WHERE T1."GroupCode" = 57) END) AS PROPERTY57,
		(CASE T0."QryGroup58" WHEN 'N' THEN '' ELSE (SELECT T1."GroupName" FROM OCQG T1 WHERE T1."GroupCode" = 58) END) AS PROPERTY58,
		(CASE T0."QryGroup59" WHEN 'N' THEN '' ELSE (SELECT T1."GroupName" FROM OCQG T1 WHERE T1."GroupCode" = 59) END) AS PROPERTY59,
		(CASE T0."QryGroup60" WHEN 'N' THEN '' ELSE (SELECT T1."GroupName" FROM OCQG T1 WHERE T1."GroupCode" = 60) END) AS PROPERTY60,
		(CASE T0."QryGroup61" WHEN 'N' THEN '' ELSE (SELECT T1."GroupName" FROM OCQG T1 WHERE T1."GroupCode" = 61) END) AS PROPERTY61,
		(CASE T0."QryGroup62" WHEN 'N' THEN '' ELSE (SELECT T1."GroupName" FROM OCQG T1 WHERE T1."GroupCode" = 62) END) AS PROPERTY62,
		(CASE T0."QryGroup63" WHEN 'N' THEN '' ELSE (SELECT T1."GroupName" FROM OCQG T1 WHERE T1."GroupCode" = 63) END) AS PROPERTY63,
		(CASE T0."QryGroup64" WHEN 'N' THEN '' ELSE (SELECT T1."GroupName" FROM OCQG T1 WHERE T1."GroupCode" = 64) END) AS PROPERTY64
		FROM "OCRD" T0;
END
