postgresql:
  database: Vikas1
  host: localhost
  password: StrongPassword123
  port: 5432
  schema: CompanyDB
  username: migration_user
sqlservers:
  anksk:
    check_new_databases: true
    password: root
    port: 1433
    server: localhost
    skip_databases: []
    sync_mode: hybrid
    username: sa
  server2:
    check_new_databases: true
    password: root
    port: 1433
    server: 192.168.18.124
    skip_databases: []
    sync_mode: hybrid
    username: sa
