postgresql:
  database: NewSaad2
  host: localhost
  password: StrongPassword123
  port: 5432
  schema: CompanyDB
  username: migration_user
sqlservers:
  server1:
    check_new_databases: true
    password: root
    port: 1433
    server: localhost
    skip_databases: []
    sync_mode: hybrid
    target_postgres_db: NewSaad6
    username: sa
