CREATE PROCEDURE OLCT_DELTA()
AS
BEGIN
		DELETE FROM ETL_LOCATION WHERE LOCCODE IN (SELECT "Code" FROM OLCT_DELTA_TABLE);
		INSERT INTO ETL_LOCATION(LOCCODE, LOCNAME)
		SELECT T0."Code", T0."Location"
		FROM "OLCT" T0 
		INNER JOIN OLCT_DELTA_TABLE TEMP ON TEMP."Code" = T0."Code"
		WHERE TEMP.OPT IN ('I', 'U');
END
