CREATE PROCEDURE ETL_PERIOD_INIT()
AS
BEGIN
	INSERT INTO ETL_PERIOD(PERIODENTRY, PERIODCODE, PERIODNAME, F_REFDATE, T_REFDATE)
	SELECT T0."AbsEntry", T0."Code", T0."Name", T0."F_RefDate", T0."T_RefDate"
	FROM "OFPR" T0;
END
