CREATE PROCEDURE OBPL_DELTA()
AS
BEGIN
		DELETE FROM ETL_BRANCH WHERE BRANCHCODE IN (SELECT "BPLId" FROM OBPL_DELTA_TABLE);
		INSERT INTO ETL_BRANCH(BRANCHCODE, BRANCHNAME)
		SELECT T0."BPLId", T0."BPLName"
		FROM "OBPL" T0 
		INNER JOIN OBPL_DELTA_TABLE TEMP ON TEMP."BPLId" = T0."BPLId"
		WHERE TEMP.OPT IN ('I', 'U');
END
